FROM ubuntu:18.04
#MAINTANER Your Name "mail2karankrishnan@gmail.com"
RUN apt-get update  && \
        apt-get install -y python3-pip
RUN mkdir -p /opt/pgm/log && \
        touch /opt/pgm/log/api.log && \
        chmod 777 /opt/pgm/log/api.log
COPY ./requirements.txt /opt/pgm/requirements.txt
WORKDIR /opt/pgm
RUN pip3 install -r requirements.txt
COPY . /opt/pgm
EXPOSE 5672 27017 15672 25672 4369
ENTRYPOINT ["/bin/bash"]
CMD ["start.sh"]
